export const browserCoreExamples = [
  "lala browser status",
  "lala browser start",
  "lala browser stop",
  "lala browser tabs",
  "lala browser open https://example.com",
  "lala browser focus abcd1234",
  "lala browser close abcd1234",
  "lala browser screenshot",
  "lala browser screenshot --full-page",
  "lala browser screenshot --ref 12",
  "lala browser snapshot",
  "lala browser snapshot --format aria --limit 200",
  "lala browser snapshot --efficient",
  "lala browser snapshot --labels",
];

export const browserActionExamples = [
  "lala browser navigate https://example.com",
  "lala browser resize 1280 720",
  "lala browser click 12 --double",
  'lala browser type 23 "hello" --submit',
  "lala browser press Enter",
  "lala browser hover 44",
  "lala browser drag 10 11",
  "lala browser select 9 OptionA OptionB",
  "lala browser upload /tmp/lala/uploads/file.pdf",
  'lala browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "lala browser dialog --accept",
  'lala browser wait --text "Done"',
  "lala browser evaluate --fn '(el) => el.textContent' --ref 7",
  "lala browser console --level error",
  "lala browser pdf",
];
